const SpanishBundle = new Map<string, string>([
	["cutscene1.1", "Esta es la historia de mi bisabuelo, Antonio, quien tenía una granja cafetera en el valle de Oporapa."],
	["cutscene1.2", "Grandes montañas habitadas por gente trabajadora conocida como “los paisas”."],
	["cutscene1.3", "Un día, cuando estaba tomando una taza de café con su hijo, su vida cambió para siempre."],
	["cutscene1.4", "El diablo apareció reclamando el alma de Antonio como suya, por su vida pecadora y degenerada."],
	["cutscene1.5", "Extendió su mano, trayendo a Antonio hace él, pero luego su hijo mayor, Aureliano, intervino."],
	["cutscene1.6", "Se lanzó hacia el diablo, tratando de proteger a su padre, pero no era rival para el príncipe infernal."],
	["cutscene1.7", "La culpa consumió a Antonio al ver como el alma de su hijo inocente tomaba su lugar como pago."],
	["cutscene1.8", "Satisfecho, el diablo voló al monte Farashon, mientras sus carcajadas llenaban la noche."],
	["cutscene1.9", "Mi bisabuelo, con lágrimas en sus ojos y machete en mano, juró vengarse."],
	["cutscene1.10", "Esta es la historia de como mi bisabuelo, Antonio Zapata, venció al diablo."],

	["title.start", "Presiona %(mainButton)s"],
	["title.newGame", "Nuevo Juego"],
	["title.continue", "Continuar"],
	["ending.1", "Con un último poderoso blandido, derrotó al diablo. E igual de rápido, le cortó su cola."],
	["ending.2", "Demandó que el alma de su hijo fuera liberada del infierno y se le permitiera descansar en paz..."],
	["ending.3", "Y con miedo de perder un cuerno, el diablo aceptó."],
	["ending.4", "Esta historia le ganaría muchas botellas de aguardiente... y a todos los incrédulos les mostraría la cola."],
	["ending.5", "Ahora, por favor... ¡Ve a dormir!"],

	["acacias.1", "El diablo creyó que podría meterse contigo..."],
	["acacias.2", "...pero él no sabe de qué es capaz Antonio Zapata."],
	["acacias.3", "Deja atrás tu finca, y ve al monte Farashon."],
	["acacias.4", "Presiona %(helpButton)s en cualquier momento para ayuda."],

	["oporapa.1", "Abandonaste tu finca y cruzaste el río Oporapa."],
	["oporapa.2", "La boca de una caverna lleva a la guarida del diablo al este."],
	["oporapa.3", "Sería buena idea visitar el pueblo que queda más adelante en el camino, antes de explorarla."],

	["help.desktop", "Comandos\n---\nMover: WASD,\n  Numpad o Flechas\n\nEnter/Espacio:\n  Pasar Turno\n\nI: Inventario\nR: Grabar Juego / Soltar Item\nESC: Cerrar Ventana\n\nEspacio para Tips"],
	["help.mobile", "Comandos\n---\nA: Pasar Turno\nB: Cerrar Ventana\n\nStart: Inventario\nSelect: Grabar Juego / Soltar Item\n\n\nPresiona A para Tips"],
	["help.tips", "Encuentra objetos en las cuevas para vender en los pueblos.\n\nMejora tu equipo y súrtete de ítems para sobrevivir.\n\nUsa la oración de escape para huir cuando lo necesites"],
	["dialog.petDog", "Acaricias al perrito."],
	["dialog.petRosita", "Ves a Rosita, tu compañera de tantos viajes. No confías tu vida en nadie más."],
	["fainted.1", "Lo último que recuerdas es que te desmayaste por tus heridas."],
	["fainted.2", "Parece que Rosita arrastró tu desgraciado trasero hasta el pueblo..."],
	["fainted.3", "Desgraciadamente, todo lo que tenías menos tu machete, carriel y ruana, se ha ido."],
	["action.drop", "Sueltas el %0s."],
	["action.drop.not", "¡Quieres conservar esto!"],
	["action.drop.cannot", "No puede soltar el %0s aquí."],

	["action.pick", "Tomas un %0s."],
	["action.pick.cant.mobile", "No puedes tomar el %0s. Presiona Select para soltar cosas desde el inventario."],
	["action.pick.cant.desktop", "No puedes tomar el %0s. Presiona [R]  para soltar cosas desde el [I]nventario."],

	["action.pick.first.1", "Encontraste un %0s."],
	["action.pick.first.2", "No es directamente útil, pero es un objeto valioso."],
	["action.pick.first.3", "Regresa a un pueblo rezándole a San Benito para venderlo."],
	["action.pick.first.4", "Luego puedes usar el dinero para mejorar tu equipo,"],
	["action.pick.first.5", "o conseguir objetos útiles para tu próximo viaje."],
	
	["action.use.how", "¿Pero como?"],
	["action.use.machete", "Blandes tu machete, haciéndolo silbar."],
	["action.use.ruana", "La justicia es para los de ruana."],
	["action.use.carriel", "Usas el carriel con orgullo."],
	["action.use.money", "No lo usemos todo en aguardiente."],
	["action.use.guaro.1", "Tu garganta quema."],
	["action.use.guaro.2", "Te sientes un poco mareado."],
	["action.use.guaro.3", "Te sientes mareado."],
	["action.use.guaro.4", "Ese entró en reversa..."],
	["action.use.guaro.5", "¡Te duele el corazón!"],
	["action.use.guaro", "¡Te sientes valiente!"],
	["action.use.coffee", "¡Te sientes como nuevo!"],
	["action.use.aguapanela", "¡Te sientes renovado!"],
	["action.use.chocolate", "¡Te sientes fuerte!"],
	["action.use.bandage.noWounds", "No tienes heridas que cubrir."],
	["action.use.bandage", "Tus heridas están cubiertas ahora."],

	["action.use.prayer.unheard", "Tu plegaria es ignorada."],
	["action.use.prayer", "Rezas a San Benito para llevarte a la seguridad. Ten fe y aguanta."],
	["action.use.prayer.escaped", "Te cubre la luz. Estás de vuelta en el valle."],
	["action.use.arepa", "Justo como hacía mamá. Te sientes mejor."],
	["action.use.dongo", "¿Rico? te sientes mejor."],

	["dialog.merchant", "Tengo de todo para vender... ¡Pregunta por lo que no veas!"],
	["dialog.merchant.offer", "Te daré %0s pesos por todo lo que no uses, ¿tenemos un trato?"],
	["dialog.merchant.sold", "Gracias por hacer negocios conmigo."],
	["dialog.merchant.noMoney", "¡No puedes pagarlo!"],
	["dialog.merchant.burdened", "Tu inventario está lleno."],

	["dialog.blacksmith.offer", "Puedo mejorar tu machete por %0s"],
	["dialog.blacksmith.noMoney", "Puedo mejorar tu machete por %0s, ¡avísame cuando tengas el dinero!"],
	["dialog.blacksmith.upgraded", "Listo. Cuídalo y no te metas en problemas."],
	["dialog.blacksmith.cancelled", "Regresa cuando estés listo."],
	["dialog.blacksmith.cap", "El mismo Diablo temería tu machete."],

	["dialog.artisan.offer", "Soy Adriana, puedo cambiar tu carriel por uno mejor por %0s, ¿qué dices?"],
	["dialog.artisan.noMoney", "Soy Adriana, puedo cambiar tu carriel por uno mejor por %0s."],
	["dialog.artisan.upgraded", "Aquí tienes, un bello trabajo de artesanía."],
	["dialog.artisan.cancelled", "Así que... ¿Qué harás más tarde hoy?"],
	["dialog.artisan.cap", "Me uniría a tu aventura, pero..."],

	["dialog.tailor.offer", "Soy Tiberio, el sastre. Puedo hacer tu ruana más fuerte por %0s. ¿Trato?"],
	["dialog.tailor.noMoney", "Soy Tiberio, el sastre. Puedo hacer tu ruana más fuerte por %0s."],
	["dialog.tailor.upgraded", "Estoy feliz por como resultó. Espero te sirva bien."],
	["dialog.tailor.cancelled", "¡Sin problemas!"],
	["dialog.tailor.cap", "Tu ruana es una obra maestra, llévala con orgullo."],

	["dialog.distillery.offer", "Manejo la destilería local. Te puedo ofrecer aguardiente por %0s. ¿Trato?"],
	["dialog.distillery.noMoney", "Manejo la destilería local. Te puedo ofrecer aguardiente por %0s."],
	["dialog.distillery.bought", "¡Bebe responsablemente!"],
	["dialog.distillery.cancelled", "¡Sin problemas!"],
	["dialog.distillery.burdened", "Te tengo un trato pero parece que llevas demasiado."],

	["dialog.priest.blessed", "Que Dios te acompañe en esta santa misión."],
	["dialog.priest.prompt", "Tráeme el Códice de Miguel y agua bendita y convertiré tu machete en el castigo de los cielos."],

	["dialog.priest.1", "Felipe salpica el códice con agua bendita y lo pone en el altar."],
	["dialog.priest.2", "\"Listo, que la interdicción comience. Arrodíllate ante el altar y recemos.\""],
	["dialog.priest.3", "\"Oh Señor, te ruego: Permite que esta herramienta se convierta en un arma para desterrar el mal de nuestras tierras,\""],
	["dialog.priest.4", "\"Que la tristeza de éste, tu hijo, Antonio, se convierta en el recipiente de tu poder manifiesto en la tierra\""],
	["dialog.priest.5", "\"Amen.\""],
	["dialog.priest.6", "Por un momento, nada pasa..."],
	["dialog.priest.7", "Pero de repente, el machete empieza a brillar, y rayos de luz emergen de él."],
	["dialog.priest.8", "La inscripción, \"Juan 1:9\", se grava milagrosamente en la hoja del machete."],
	["dialog.priest.9", "\"Para bien o para mal, hecho está. Perdóname por poner este peso sobre ti\""],

	["dialog.guts.1", "Se te acaba la berraquera. Esto es peligroso."],
	["dialog.guts.2", "Cuando tu berraquera sea cero, recibirás heridas directamente,"],
	["dialog.guts.3", "y tus machetazos serán débiles."],
	["dialog.guts.4", "Bebe o come algo para fortalecerte,"],
	["dialog.guts.5", "Y si las cosas se ponen feas, reza a San Benito para huir de las cuevas."],
	["dialog.guts.6", "De ésta manera conservas el tesoro que has encontrado."],

	["dialog.combat.1", "Es hora de enfrentar enemigos en combate..."],
	["dialog.combat.2", "Las lecciones enseñadas por Don Abelardo, tu padre, te vienen a la mente."],
	["dialog.combat.3", "Ataca los enemigos moviéndote hacia ellos."],
	["dialog.combat.4", "Los resultados del ataque son los números, representando el daño."],
	["dialog.combat.5", "Junto al icono del \"rayo\", puedes ver tu \"berraquera\"."],
	["dialog.combat.6", "Cuando evades un ataque, tu berraquera baja."],
	["dialog.combat.7", "Si te quedas sin berraquera, ataques de enemigos subsiguientes te causarán una herida."],
	["dialog.combat.8", "Puedes ver tu vitalidad al lado del icono del \"corazón\","],
	["dialog.combat.9", "Cada herida los reduce en uno, y si llega a cero, te desmayarás."],
	["dialog.combat.10", "Puedes restaurar tu berraquera y heridas con ciertos objetos."],
	["dialog.combat.11.mobile", "Finalmente, recuerda que puedes presionar A para pasar tu turno."],
	["dialog.combat.11.desktop", "Finalmente, recuerda que puedes presionar Espacio para pasar tu turno."],

	["dialog.says", "%0s dice:"],

	["dialog.npc.1", "Solo una hoja bendita puede matar al Diablo."],
	["dialog.npc.2", "Un hombre santo vivía en una cueva al sur del valle."],
	["dialog.npc.3", "Mejora tu machete o no tendrás una oportunidad."],
	["dialog.npc.4", "El laurel en tu sopa mejora su aroma."],
	["dialog.cat", "¡Miauuuuuuu!"],
	["dialog.chicken", "¡Clocló!"],
	["dialog.chick", "¡Pio Pio!"],
	
	["key.space", "Espacio"],

	["items.machete", "Machete"],
	["items.ruana", "Ruana"],
	["items.carriel", "Carriel"],
	["items.money", "Plata"],
	["items.aguardiente", "Aguardiente"],
	["items.coffee", "Café"],
	["items.aguapanela", "Aguapanela"],
	["items.chocolate", "Chocolate"],
	["items.bandage", "Vendaje"],
	["items.escapePrayer", "Oración de escape"],
	["items.arepa", "Arepa"],
	["items.dongo", "Dongo"],
	["items.shovel", "Pala"],
	["items.axe", "Hacha"],
	["items.holyWater", "Agua bendita"],
	["items.knife", "Cuchillo"],
	["items.crucifix", "Crucifijo"],
	["items.tunjo", "Tunjo"],
	["items.codex", "Códice de Miguel"],

	["items.machete.description", "¡Corta casi todo! Menos las deudas..."],
	["items.ruana.description", "Te protege del frío y el daño."],
	["items.carriel.description", "Te permite cargar cosas."],
	["items.money.description", "Compra objetos útiles en los pueblos."],
	["items.aguardiente.description", "Aumenta tu coraje, no lo tomes a la ligera."],
	["items.coffee.description", "Cosecha fresca de Minas Rojas"],
	["items.aguapanela.description", "Energizante hecho de caña de azúcar."],
	["items.chocolate.description", "Bebida deliciosa ¡échale queso adentro!"],
	["items.bandage.description", "Cubre heridas y las mantiene limpias."],
	["items.escapePrayer.description", "Santa estampa de San Benito, patrono de los exploradores."],
	["items.arepa.description", "¿Es un pastel de maíz? ¡No! ¡Es una arepa!"],
	["items.dongo.description", "Un salado hongo sanador."],
	["items.shovel.description", "Cámbialo en los pueblos por dinero."],
	["items.axe.description", "Cámbialo en los pueblos por dinero."],
	["items.holyWater.description", "Usado en rituales sagrados."],
	["items.knife.description", "Cámbialo en los pueblos por dinero."],
	["items.crucifix.description", "Cámbialo en los pueblos por dinero."],
	["items.tunjo.description", "Cámbialo en los pueblos por dinero."],
	["items.codex.description", "Un libro con imágenes del Arcángel Miguel derrotando al diablo."],

	["items.aguardiente.effect", "+30 Berraquera"],
	["items.coffee.effect", "+15 Berraquera"],
	["items.aguapanela.effect", "+15 Berraquera"],
	["items.chocolate.effect", "+15 Berraquera"],
	["items.bandage.effect", "-5 heridas"],
	["items.arepa.effect", "-3 heridas"],
	["items.dongo.effect", "-1 heridas"],

	["items.machete.blessedPrefix", "Bendito"],

	["items.level", "Nivel %0s"],
	["items.attack", "Ataque %0s"],
	["items.evade", "Evade %0s%%"],
	["items.carry", "%0s objetos"],

	["items.currentMoney", "Dinero: %0s pesos"],
	["ui.buyPrompt.mobile", "A para comprar"],
	["ui.buyPrompt.desktop", "Enter para comprar"],

	["ui.prompt.desktop", "[Y/N]"],
	["ui.prompt.mobile", "[A para confirmar]"],

	["save.prompt", "Guardar Partida?"],
	["save.saving", "Guardando"],
	["save.saved", "Partida Guardada."],

	["save.notFound", "No se encontró partida grabada"],
	["save.versionMismatch", "Lo siento, tu partida es de una versión antigua (#%0s)"],
	["save.loadError", "Error cargando la partida."],

	
	["animal.mule", "mula"],
	["npc.townsman", "pueblerino"],
	["animal.dog", "perro"],
	["animal.cat", "gato"],
	["animal.chicken", "gallina"],
	["animal.chick", "pollito"],
	["npc.merchant", "mercader"],

	["animal.mule.the", "La mula"],
	["npc.townsman.the", "El pueblerino"],
	["animal.dog.the", "El perro"],
	["animal.cat.the", "El gato"],
	["animal.chicken.the", "La gallina"],
	["animal.chick.the", "El pollito"],
	["npc.merchant.the", "El mercader"],

	["monster.visage", "visage"],
	["monster.bat", "guácharo"],
	["monster.goblin", "duende"],
	["monster.monkey", "mico"],
	["monster.caiman", "caimán"],
	["monster.puma", "puma"],
	["monster.jaguar", "jaguar"],
	["monster.crocodile", "cocodrilo"],

	["dialog.daniel", "Vengo del frío altiplano de Santa Fé, ¡me gusta este clima!"],
	["dialog.alejandro", "¡Papá! ¡Papá! ¡Quiero saberlo todo!"],
]);

export default SpanishBundle;